version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=user_api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]
    volumes:
      - .:/app
      - ./flask_session:/app/flask_session
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=super-secret-key-123456
      - FLASK_APP=run.py
    networks:
      - app-network

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
